# -*- coding: utf-8 -*-

from odoo import models, fields, api

class declaivamensal(models.Model):
    _name = 'declarar.iva'
    #_rec_name = 'name'
    _description = 'Declaração Iva Mernsal'
    ano = fields.Date(string='Ano')
    mes = fields.Selection([('janeior','Janeiro'),('fevereiro','Fevereiro'),('marco','Março'),('abril','Abril'),('Maio','Maio'),('junho','Junho'),('julho','Julho'),('agosto','Agosto'),('setembro','Setembro'),('outubro','Outubro'),('novembro','Novembro'),('dezembro','Dezembor'),], string='Mes')
    processar = fields.Boolean(string='Processar')
    formulario = fields.Selection([('modelo106','Modelo 106'),('anexocliente','Anexo Cliente'),('anexofornecidor','Anexo Fornecedores')], string='Formulario', default='modelo106', widget = 'radio')
    accao = fields.Selection([('imprimir','Imprimir'),('exportarpdf','Exportar PDF'),('exportarxml','Exportar XML')], string='Acção', default='imprimir', widget = 'radio')

    dados_fatura_client = fields.One2many('fatuclient.fatuclient', 'fatuclient_id', string="Anexo Clientes", required=False,)
    dados_fatura_fornecedores = fields.One2many('despesa.despesa', 'id', string="Anexo Fornecedores", required=False)

    tipo_declar = fields.Selection(
        [('noprazo', 'No Prazo'), ('foraprazo', 'Fora do Prazo'), ('substituição', 'Substituição')], string='Tipo',
        default='noprazo', widget='radio')
    clientes = fields.Boolean(string='Clientes')
    fornecidores = fields.Boolean(string='Fornecedores')
    regularizacao_clientes = fields.Boolean(string='Regularização Cliente')
    regularizacao_fornecidores = fields.Boolean(string='Regularização Fornecedores')
    nao_real_operac = fields.Boolean(string='Não Realizo Operações')
    realizo_uma_unica_operac = fields.Boolean(string='Realizo uma unica Operações')

    campo1 = fields.Float('01')
    campo2 = fields.Float('02')
    campo3 = fields.Float('03')
    campo4 = fields.Float('04')
    campo5 = fields.Float('05')
    campo6 = fields.Float('06')
    campo7 = fields.Float('07')
    campo8 = fields.Float('08')
    campo9 = fields.Float('09')
    campo10 = fields.Float('10')
    campo11 = fields.Float('11')
    campo12 = fields.Float('12')
    campo13 = fields.Float('13')
    campo14 = fields.Float('14')
    campo15 = fields.Float('15')
    campo16 = fields.Float('16')
    campo17 = fields.Float('17')
    campo18 = fields.Float('18')
    campo19 = fields.Float('19')
    campo20 = fields.Float('20')
    campo21 = fields.Float('21')
    campo22 = fields.Float('22')
    campo23 = fields.Float('23')
    campo24 = fields.Float('24')
    campo25 = fields.Float('25')
    campo26 = fields.Float('26')
    campo27 = fields.Float('27')
    campo28 = fields.Float('28')
    campo29 = fields.Float('29')
    campo30 = fields.Float('30')
    campo31 = fields.Float('31')
    campo32 = fields.Float('32')
    campo33 = fields.Float('33')
    campo34 = fields.Float('34')
    campo35 = fields.Float('35')
    campo36 = fields.Float('36')
    campo37 = fields.Float('37')
    campo38 = fields.Float('38')
    campo39 = fields.Float('39')
    campo40 = fields.Float('40')
    campo41 = fields.Float('41')
    campo42 = fields.Float('42')
    campo43 = fields.Float('43')
    campo44 = fields.Float('44')
    campo45 = fields.Float('45')
    campo46 = fields.Float('46')
    campo47 = fields.Float('47')
    campo48 = fields.Float('48')
    campo49 = fields.Float('49')
    campo50 = fields.Float('50')
    lugar = fields.Char(string='Lugar')
    data = fields.Date(string='Data')
    obs = fields.Text(string='obs')
