# -*- coding: utf-8 -*-

from odoo import models, fields, api

class veiculoRequerimento(models.Model):
     _name = 'veiculo.requerimento'
     _description = "Veiculos Requerimento"

     campo_1 = fields.Char()
     nome = fields.Char()
     documento = fields.Char()
     emitido_em = fields.Date()
     por = fields.Char()
     data_nascimento = fields.Date()
     nacionlidade = fields.Char()
     residencia = fields.Char()
     localidade = fields.Char()
     data = fields.Date()
     matricula_veiculo = fields.Char()
     data_matricula = fields.Date()
     matricula_inicial = fields.Boolean()
     livrete_anterior = fields.Boolean()
     cancelamento = fields.Boolean()
     titulo_propiedade = fields.Boolean()
     mudanca_cor = fields.Boolean()
     verbete_despacho_alfandiga = fields.Boolean()
     alteracao_de = fields.Boolean()
     folha_homolagacao = fields.Boolean()
     catalogos = fields.Boolean()
     segunda_via = fields.Boolean()
     certificados_caracteristicas = fields.Boolean()
     periodica = fields.Boolean()
     transformacao = fields.Boolean()
     acidente = fields.Boolean()
     marca = fields.Char()
     caixa_tipo = fields.Char()
     modelo = fields.Char()
     cor = fields.Char()
     cateforia = fields.Char()
     pneus_frent = fields.Char()
     ano_fabrico = fields.Char()
     pneus_ret = fields.Char()
     numero_chassi = fields.Integer()
     lotacao = fields.Char()
     motor_num_cilindro = fields.Integer()
     pesso_bruto = fields.Float()
     motor_cilindrada = fields.Float()
     tara = fields.Float()
     mutor_combustivel = fields.Char()
     servico = fields.Char()
     caixa_demencao = fields.Char()
     obs = fields.Char()
     num_copia = fields.Integer()

